In [37]:
import xgboost
import pandas as pd
import numpy as np
import math
from pyspark.context import SparkContext

In [3]:
data = pd.read_csv('/home/palaniappan/Downloads/Validation_Train.csv',sep = ',')

In [38]:
d = spark.read.csv('/home/palaniappan/Downloads/Validation_Train.csv')

NameError: name 'spark' is not defined

In [4]:
data.head(3)

,date,volume_actuals,Average_Temperature,EasterDay,GoodFriday,NewYear,Christmas,Labor,Columbus,Independence,...,CONCACAF,Corona,Vive,Holidays,Working_Days,Weekends,preciocliente_hl,ingresonto_hl,month,lag12
0,201301,71.3124,19.639286,0,0,1,0,0,0,0,...,0,0,0,1,22,8,1884.43,1773.37,1,71.3124
1,201302,71.7384,20.020000,0,0,0,0,0,0,0,...,0,0,0,1,19,8,1872.66,1771.20,2,71.7384
2,201303,123.2844,25.626667,1,1,0,0,0,0,0,...,0,0,1,4,18,9,1917.73,1802.98,3,123.2844

In [9]:
data[list(set(data.columns) - set(data.volume_actuals))]

,FIFA,Constitution,Weekends,preciocliente_hl,month,Benito.Juarez,Average_Temperature,Central,Christmas,Independence,...,lag12,EasterDay,Corona,date,Labor,volume_actuals,Revolution,GoodFriday,ingresonto_hl,NewYear
0,0,0,8,1884.43,1,0,19.639286,0,0,0,...,71.3124,0,0,201301,0,71.3124,0,0,1773.37,1
1,0,1,8,1872.66,2,0,20.020000,0,0,0,...,71.7384,0,0,201302,0,71.7384,0,0,1771.20,0
2,0,0,9,1917.73,3,1,25.626667,0,0,0,...,123.2844,1,0,201303,0,123.2844,0,1,1802.98,0
3,0,0,8,1825.08,4,0,27.160000,0,0,0,...,121.4952,0,0,201304,0,121.4952,0,0,1728.66,0
4,0,0,7,2107.25,5,0,29.774194,0,0,0,...,135.9792,0,0,201305,1,135.9792,0,0,1868.57,0
5,0,0,10,2726.37,6,0,33.300000,0,0,0,...,17.2104,0,0,201306,0,17.2104,0,0,2316.12,0
6,0,0,8,2043.29,7,0,34.117241,0,0,0,...,113.0604,0,0,201307,0,113.0604,0,0,1696.67,0
7,0,0,9,2066.36,8,0,34.513333,0,0,0,...,292.1508,0,0,201308,0,292.1508,0,0,1728.83,0
8,0,0,9,2046.63,9,0,34.003333,0,0,1,...,250.9992,0,0,201309,0,250.9992,0,0,1700.91,0
9,0,0,8,2106.02,10,0,28.016667,0,0,0,...,258.5820,0,1,201310,0,258.5820,0,0,1852.50,0
10,0,0,8,2077.85,11,0,24.703333,0,0,0,...,165.6288,0,0,201311,0,165.6288,1,0,1825.72,0
11,0,0,9,2065.98,12,0,20.835714,0,1,0,...,176.0232,0,0,201312,0,176.0232,0,0,1702.60,0
12,0,0,8,2000.41,1,0,23.888889,0,0,0,...,71.3124,0,0,201401,0,152.0820,0,0,1583.58,1
13,0,1,8,2016.92,2,0,23.855556,0,0,0,...,71.7384,0,0,201402,0,266.3352,0,0,1697.91,0
14,0,0,10,1996.25,3,1,25.666667,0,0,0,...,123.2844,0,0,201403,0,323.8452,0,0,1681.40,0
15,0,0,7,2026.56,4,0,27.366667,0,0,0,...,121.4952,1,0,201404,0,237.2820,0,1,1561.81,0
16,0,0,8,2123.62,5,0,30.329630,0,0,0,...,135.9792,0,0,201405,1,251.3400,0,0,1547.71,0
17,0,0,9,1975.59,6,0,33.885185,0,0,0,...,17.2104,0,0,201406,0,371.8128,0,0,1724.69,0
18,0,0,8,2008.96,7,0,35.400000,0,0,0,...,113.0604,0,0,201407,0,499.5276,0,0,1764.83,0
19,0,0,10,2090.86,8,0,34.896667,0,0,0,...,292.1508,0,0,201408,0,702.8148,0,0,1886.90,0
20,0,0,8,2026.19,9,0,34.656667,0,0,1,...,250.9992,0,0,201409,0,682.7076,0,0,1905.21,0
21,0,0,8,1985.67,10,0,30.668750,0,0,0,...,258.5820,0,1,201410,0,697.5324,0,0,1754.19,0
22,0,0,9,2107.87,11,0,26.019355,1,0,0,...,165.6288,0,0,201411,0,410.2380,1,0,1710.34,0
23,0,0,8,1977.03,12,0,20.925806,0,1,0,...,176.0232,0,0,201412,0,360.0552,0,0,1753.35,0
24,0,0,9,2004.94,1,0,21.867742,0,0,0,...,152.0820,0,0,201501,0,284.1420,0,0,1711.90,1
25,0,1,8,1991.81,2,0,24.825000,0,0,0,...,266.3352,0,0,201502,0,435.2016,0,0,1541.69,0
26,0,0,9,1981.49,3,1,26.856250,0,0,0,...,323.8452,0,0,201503,0,696.4248,0,0,1589.56,0
27,0,0,7,1965.17,4,0,26.940625,0,0,0,...,237.2820,1,0,201504,0,685.6044,0,1,1630.24,0
28,0,0,9,1993.41,5,0,26.636364,0,0,0,...,251.3400,0,0,201505,1,644.1972,0,0,1601.09,0
29,0,0,8,2137.69,6,0,33.330303,0,0,0,...,371.8128,0,0,201506,0,747.2040,0,0,1705.80,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34,0,0,9,2158.28,11,0,23.764706,0,0,0,...,410.2380,0,1,201511,0,380.1624,1,0,1569.02,0
35,0,0,7,2160.77,12,0,19.715152,0,1,0,...,360.0552,0,0,201512,0,704.0928,0,0,1886.22,0
36,0,0,10,2138.44,1,0,19.833333,0,0,0,...,284.1420,0,0,201601,0,298.4556,0,0,1925.93,1
37,0,1,8,2108.08,2,0,26.365517,0,0,0,...,435.2016,0,0,201602,0,383.4000,0,0,1909.86,0
38,0,0,7,2186.00,3,1,25.834483,0,0,0,...,696.4248,1,0,201603,0,664.3044,0,1,1596.07,0
39,0,0,9,2340.79,4,0,27.438462,0,0,0,...,685.6044,0,0,201604,0,488.1960,0,0,1397.67,0
40,0,0,8,2282.05,5,0,28.034483,0,0,0,...,644.1972,0,0,201605,1,445.5960,0,0,1226.26,0
41,0,0,8,2379.89,6,0,33.931759,0,0,0,...,747.2040,0,0,201606,0,594.3552,0,0,1568.25,0
42,0,0,10,2391.00,7,0,36.081379,0,0,0,...,506.2584,0,0,201607,0,667.2864,0,0,1602.36,0
43,0,0,8,2517.62,8,0,35.264862,0,0,0,...,574.7592,0,0,201608,0,471.9894,0,0,1751.85,0
44,0,0,8,2578.11,9,0,32.979103,0,0,1,...,641.0448,0,0,201609,0,439.1208,0,0,1870.16,0
45,0,0,10,2537.69,10,0,31.296774,0,0,0,...,506.7696,0,0,201610,0,374.7036,0,0,1911.29,0
46,0,0,8,2561.00,11,0,24.890742,0,0,0,...,380.1624,0,1,201611,0,392.3600,1,0,1856.19,0
47,0,0,8,2570.78,12,0,20.839864,0,1,0,...,704.0928,0,0,201612,0,448.4600,0,0,1878.98,0
48,0,0,8,2537.11,1,0,23.688321,0,0,0,...,298.4556,0,0,201701,0,225.5050,0,0,1910.06,1
49,0,1,8,2553.30,2,0,21.918070,0,0,0,...,383.4000,0,0,201702,0,323.8500,0,0,1793.14,0
50,0,0,8,2610.51,3,1,26.386394,0,0,0,...,664.3044,0,0,201703,0,794.6558,0,0,1445.36,0
51,0,0,9,2570.19,4,0,28.340805,0,0,0,...,488.1960,1,0,201704,0,353.4096,0,1,1566.49,0
52,0,0,8,2607.07,5,0,28.399933,0,0,0,...,445.5960,0,0,201705,1,1389.6120,0,0,1406.24,0
53,0,0,8,2594.58,6,0,39.700000,0,0,0,...,594.3552,0,0,201706,0,193.7448,0,0,1483.36,0
54,0,0,10,2624.33,7,0,39.461290,0,0,0,...,667.2864,0,0,201707,0,1169.2848,0,0,1451.46,0
55,0,0,8,2614.77,8,0,40.035484,0,0,0,...,471.9894,0,0,201708,0,537.3564,0,0,1637.63,0
56,0,0,8,2595.62,9,0,39.590323,0,0,1,...,439.1208,0,0,201709,0,1055.8836,0,0,1652.80,0
57,0,0,9,2585.42,10,0,37.948387,0,0,0,...,374.7036,0,0,201710,0,806.5884,0,0,1684.47,0
58,0,0,8,2589.97,11,0,32.987097,0,0,0,...,392.3600,0,1,201711,0,761.1768,1,0,1685.52,0
59,0,0,10,2719.47,12,0,20.579134,0,1,0,...,448.4600,0,0,201712,0,991.1316,0,0,1638.17,0
60,0,0,8,2750.19,1,0,21.783514,0,0,0,...,225.5050,0,0,201801,0,617.5296,0,0,1698.63,1
61,0,1,8,2753.65,2,0,23.396829,0,0,0,...,323.8500,0,0,201802,0,701.6220,0,0,1651.65,0
62,0,0,9,2706.78,3,1,26.074092,0,0,0,...,794.6558,0,0,201803,0,888.0396,0,1,1656.72,0
63,0,0,8,2753.42,4,0,27.449312,0,0,0,...,353.4096,1,0,201804,0,733.9128,0,0,1673.38,0

In [15]:
xgb = xgboost.XGBRegressor(n_estimators=100, learning_rate=0.08, gamma=0, subsample=0.75,
                           colsample_bytree=1, max_depth=7)

In [16]:
traindf, testdf = pd.read_csv('/home/palaniappan/Downloads/Validation_Train.csv')\
,pd.read_csv('/home/palaniappan/Downloads/Validation_Test.csv')
X = data[list(set(data.columns) - set(data.volume_actuals))]
y = data['volume_actuals']
xgb.fit(X,y)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.08, max_delta_step=0,
       max_depth=7, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=0.75)

In [23]:
testdf.columns
X_test = testdf[list(set(data.columns) - set(testdf.volume_actuals))]

In [26]:
predictions = xgb.predict(X_test)
predictions

array([ 800.39294434], dtype=float32)

In [29]:
predictions[0]

800.39294

In [30]:
print 'Accuracy: ',(1 - abs(predictions[0] - 802)/802)*100

Accuracy:  99.7996189945